# [START gae_python37_cloudsql_config]
runtime: python37
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  CLOUD_SQL_USERNAME: prembhanderi
  CLOUD_SQL_PASSWORD: justguess
  CLOUD_SQL_DATABASE_NAME: mydatabase
  CLOUD_SQL_CONNECTION_NAME: ece-461-pyapi:us-east1:project2-mysql-database
  GITHUB_TOKEN: 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
  # [END gae_python37_cloudsql_config]
