name: Deploy to Google app engine
on:
  push:
    branches:
      - main
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}