name: Deploy to google app engine
on:
  push:
    branches:
      - main
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions-hub/gcloud@master
          env:
            PROJECT_ID: ${{secrets.GCLOUD_PROJECT}}
            APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_API_KEYFILE}}
          with:
            args: app deploy app.yaml --no-promote --project ${{secrets.GCLOUD_PROJECT}} -v staging