name: Deploy to Google app engine
on:
  push:
    branches:
      - main
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Login
    - uses: actions/checkout@v2
    - uses: google-github-actions/deploy-appengine@main
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
    - name: Deploy
      run: |
        run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --region us-central1 --platform managed