name: test API 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: [3.9]
    env:
      GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
      LOG_FILE: log.txt
    steps:
    - uses: actions/checkout@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: 
        python3 -m pip install pytest
    - name: Run pytest
      run:
        pytest .github/workflows/test_api.py